repos:

# - repo: ...

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [cust, Fix, test] # optional: list of Conventional Commits types to allow
